export function custom({ title, message, color }: {
    title?: string;
    message?: string;
    color?: string;
}): void;
export function info(message?: string): void;
export function success(message?: string): void;
export function warning(message?: string): void;
export function error(message?: string): void;
export function separator(char?: string, length?: number): void;
export function red(message: any): string;
export function blue(message: any): string;
export function magenta(message: any): string;
export function white(message: any): string;
export function black(message: any): string;
export function green(message: any): string;
export function yellow(message: any): string;
export function cyan(message: any): string;
export function bgred(message: any): string;
export function bgblue(message: any): string;
export function bgmagenta(message: any): string;
export function bgwhite(message: any): string;
export function bgblack(message: any): string;
export function bggreen(message: any): string;
export function bgyellow(message: any): string;
export function bgcyan(message: any): string;
export function reset(message: any): string;
export function bold(message: any): string;
export function dim(message: any): string;
export function italic(message: any): string;
export function reverse(message: any): string;
export function underscore(message: any): string;
export function strikethrough(message: any): string;
export function backoneline(message: any): string;
export function cleanthisline(message: any): string;
